theme = "gruvybox"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inline-hints = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
